cache:
  capacity: 1000
  data-loss-interval: 30

server:
  port: 8181
  servlet:
    context-path: /app

spring:
  flyway:
    locations: classpath:db.migration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./hw13-persistent-cache/data/appdb;MODE=PostgreSQL
    username: userDb
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE