server:
  port: 8182
  servlet:
    context-path: /app
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: hw17-https-second-app/chaos2.p12
    key-store-password: 123456
    key-alias: chaos2